services:
  - type: web
    name: subwallet-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    # Add your environment variables here:
    # - key: MONGODB_URI
    #   value: your-mongodb-connection-string
    # - key: JWT_SECRET
    #   generateValue: true
    # - key: GOOGLE_CLIENT_ID
    #   sync: false
    # - key: GOOGLE_CLIENT_SECRET
    #   sync: false
    # - key: OPENAI_API_KEY
    #   sync: false